# This workflow uses actions that are not certified by GitHub.
# São fornecidas por terceiros e regidas por
# termos de serviço, política de privacidade e suporte separados
# documentação.

name: Weekly Team Sync
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Criação de issue"
        required: false
        default: "Issue criada"
    
  schedule:
    - cron: 0 12 * * 4

env:
    MONTH_01: "Janeiro"
    MONTH_02: "Fevereiro"
    MONTH_03: "Março"
    MONTH_04: "Abril"
    MONTH_05: "Maio"
    MONTH_06: "Junho"
    MONTH_07: "Julho"
    MONTH_08: "Agosto"
    MONTH_09: "Setembro"
    MONTH_10: "Outubro"
    MONTH_11: "Novembro"
    MONTH_12: "Dezembro"

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set current day
        id: day
        run: echo "::set-output name=day::$(date -d 'next wednesday' +%d)"

      - name: Set current month
        id: month
        run: echo "::set-output name=month::$(date -d 'next wednesday' +%m)"

      - name: Set final month name
        id: month_name
        run: echo "::set-output name=month_name::${!MONTH_NAME_VAR}"
        env:
          MONTH_NAME_VAR: MONTH_${{ steps.month.outputs.month }}

      - name: Set the current year
        id: year
        run: echo "::set-output name=year::$(date -d 'next wednesday' +%Y)"

      - name: Create meeting issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        env:
          DAY: ${{ steps.day.outputs.day }}
          MONTH_NAME: ${{ steps.month_name.outputs.month_name }}
          YEAR: ${{ steps.year.outputs.year }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ""
          labels: "reunião"
          title: "[Reunião] Geral: $DAY de $MONTH_NAME de $YEAR"
          body: |
            # Reunião <Grupo de trabalho ou tema da reunião>

            - Data: <! –– data ––>
            - Participantes:
              - Nome e Sobrenome (@Github ou E-mail)

            ## Ata

            _Adicione os itens que foram discutidos durante a reunião._

            -

            ### Ações para serem realizadas

            - [ ] Atividade (@responsável)
            - [ ]
          pinned: true
          close-previous: false
